#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodyServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbFoody")]
	public partial class DBFoodyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDanhMuc(DanhMuc instance);
    partial void UpdateDanhMuc(DanhMuc instance);
    partial void DeleteDanhMuc(DanhMuc instance);
    partial void InsertThanhPho(ThanhPho instance);
    partial void UpdateThanhPho(ThanhPho instance);
    partial void DeleteThanhPho(ThanhPho instance);
    partial void InsertQuanHuyen(QuanHuyen instance);
    partial void UpdateQuanHuyen(QuanHuyen instance);
    partial void DeleteQuanHuyen(QuanHuyen instance);
    partial void InsertDuongPho(DuongPho instance);
    partial void UpdateDuongPho(DuongPho instance);
    partial void DeleteDuongPho(DuongPho instance);
    partial void InsertQuanAn(QuanAn instance);
    partial void UpdateQuanAn(QuanAn instance);
    partial void DeleteQuanAn(QuanAn instance);
    partial void InsertMonAn(MonAn instance);
    partial void UpdateMonAn(MonAn instance);
    partial void DeleteMonAn(MonAn instance);
    #endregion
		
		public DBFoodyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbFoodyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBFoodyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBFoodyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBFoodyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBFoodyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DanhMuc> DanhMucs
		{
			get
			{
				return this.GetTable<DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<ThanhPho> ThanhPhos
		{
			get
			{
				return this.GetTable<ThanhPho>();
			}
		}
		
		public System.Data.Linq.Table<QuanHuyen> QuanHuyens
		{
			get
			{
				return this.GetTable<QuanHuyen>();
			}
		}
		
		public System.Data.Linq.Table<DuongPho> DuongPhos
		{
			get
			{
				return this.GetTable<DuongPho>();
			}
		}
		
		public System.Data.Linq.Table<QuanAn> QuanAns
		{
			get
			{
				return this.GetTable<QuanAn>();
			}
		}
		
		public System.Data.Linq.Table<MonAn> MonAns
		{
			get
			{
				return this.GetTable<MonAn>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMuc")]
	public partial class DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanhMuc;
		
		private string _TenDanhMuc;
		
		private System.Data.Linq.Binary _HinhDanhMuc;
		
		private System.Nullable<int> _KieuDanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanhMucChanging(int value);
    partial void OnMaDanhMucChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    partial void OnHinhDanhMucChanging(System.Data.Linq.Binary value);
    partial void OnHinhDanhMucChanged();
    partial void OnKieuDanhMucChanging(System.Nullable<int> value);
    partial void OnKieuDanhMucChanged();
    #endregion
		
		public DanhMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhMuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanhMuc
		{
			get
			{
				return this._MaDanhMuc;
			}
			set
			{
				if ((this._MaDanhMuc != value))
				{
					this.OnMaDanhMucChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMuc = value;
					this.SendPropertyChanged("MaDanhMuc");
					this.OnMaDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(100)")]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhDanhMuc", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhDanhMuc
		{
			get
			{
				return this._HinhDanhMuc;
			}
			set
			{
				if ((this._HinhDanhMuc != value))
				{
					this.OnHinhDanhMucChanging(value);
					this.SendPropertyChanging();
					this._HinhDanhMuc = value;
					this.SendPropertyChanged("HinhDanhMuc");
					this.OnHinhDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KieuDanhMuc", DbType="Int")]
		public System.Nullable<int> KieuDanhMuc
		{
			get
			{
				return this._KieuDanhMuc;
			}
			set
			{
				if ((this._KieuDanhMuc != value))
				{
					this.OnKieuDanhMucChanging(value);
					this.SendPropertyChanging();
					this._KieuDanhMuc = value;
					this.SendPropertyChanged("KieuDanhMuc");
					this.OnKieuDanhMucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhPho")]
	public partial class ThanhPho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TenThanhPho;
		
		private EntitySet<QuanHuyen> _QuanHuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTenThanhPhoChanging(string value);
    partial void OnTenThanhPhoChanged();
    #endregion
		
		public ThanhPho()
		{
			this._QuanHuyens = new EntitySet<QuanHuyen>(new Action<QuanHuyen>(this.attach_QuanHuyens), new Action<QuanHuyen>(this.detach_QuanHuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThanhPho", DbType="NVarChar(50)")]
		public string TenThanhPho
		{
			get
			{
				return this._TenThanhPho;
			}
			set
			{
				if ((this._TenThanhPho != value))
				{
					this.OnTenThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._TenThanhPho = value;
					this.SendPropertyChanged("TenThanhPho");
					this.OnTenThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhPho_QuanHuyen", Storage="_QuanHuyens", ThisKey="id", OtherKey="MaTP")]
		public EntitySet<QuanHuyen> QuanHuyens
		{
			get
			{
				return this._QuanHuyens;
			}
			set
			{
				this._QuanHuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuanHuyens(QuanHuyen entity)
		{
			this.SendPropertyChanging();
			entity.ThanhPho = this;
		}
		
		private void detach_QuanHuyens(QuanHuyen entity)
		{
			this.SendPropertyChanging();
			entity.ThanhPho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanHuyen")]
	public partial class QuanHuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TenQuanHuyen;
		
		private System.Nullable<int> _MaTP;
		
		private EntitySet<DuongPho> _DuongPhos;
		
		private EntityRef<ThanhPho> _ThanhPho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTenQuanHuyenChanging(string value);
    partial void OnTenQuanHuyenChanged();
    partial void OnMaTPChanging(System.Nullable<int> value);
    partial void OnMaTPChanged();
    #endregion
		
		public QuanHuyen()
		{
			this._DuongPhos = new EntitySet<DuongPho>(new Action<DuongPho>(this.attach_DuongPhos), new Action<DuongPho>(this.detach_DuongPhos));
			this._ThanhPho = default(EntityRef<ThanhPho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuanHuyen", DbType="NVarChar(30)")]
		public string TenQuanHuyen
		{
			get
			{
				return this._TenQuanHuyen;
			}
			set
			{
				if ((this._TenQuanHuyen != value))
				{
					this.OnTenQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuanHuyen = value;
					this.SendPropertyChanged("TenQuanHuyen");
					this.OnTenQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTP", DbType="Int")]
		public System.Nullable<int> MaTP
		{
			get
			{
				return this._MaTP;
			}
			set
			{
				if ((this._MaTP != value))
				{
					if (this._ThanhPho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTPChanging(value);
					this.SendPropertyChanging();
					this._MaTP = value;
					this.SendPropertyChanged("MaTP");
					this.OnMaTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanHuyen_DuongPho", Storage="_DuongPhos", ThisKey="id", OtherKey="MaQuan")]
		public EntitySet<DuongPho> DuongPhos
		{
			get
			{
				return this._DuongPhos;
			}
			set
			{
				this._DuongPhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThanhPho_QuanHuyen", Storage="_ThanhPho", ThisKey="MaTP", OtherKey="id", IsForeignKey=true)]
		public ThanhPho ThanhPho
		{
			get
			{
				return this._ThanhPho.Entity;
			}
			set
			{
				ThanhPho previousValue = this._ThanhPho.Entity;
				if (((previousValue != value) 
							|| (this._ThanhPho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThanhPho.Entity = null;
						previousValue.QuanHuyens.Remove(this);
					}
					this._ThanhPho.Entity = value;
					if ((value != null))
					{
						value.QuanHuyens.Add(this);
						this._MaTP = value.id;
					}
					else
					{
						this._MaTP = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThanhPho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuongPhos(DuongPho entity)
		{
			this.SendPropertyChanging();
			entity.QuanHuyen = this;
		}
		
		private void detach_DuongPhos(DuongPho entity)
		{
			this.SendPropertyChanging();
			entity.QuanHuyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuongPho")]
	public partial class DuongPho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDuong;
		
		private string _TenDuong;
		
		private System.Nullable<int> _MaQuan;
		
		private EntitySet<QuanAn> _QuanAns;
		
		private EntityRef<QuanHuyen> _QuanHuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDuongChanging(int value);
    partial void OnMaDuongChanged();
    partial void OnTenDuongChanging(string value);
    partial void OnTenDuongChanged();
    partial void OnMaQuanChanging(System.Nullable<int> value);
    partial void OnMaQuanChanged();
    #endregion
		
		public DuongPho()
		{
			this._QuanAns = new EntitySet<QuanAn>(new Action<QuanAn>(this.attach_QuanAns), new Action<QuanAn>(this.detach_QuanAns));
			this._QuanHuyen = default(EntityRef<QuanHuyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDuong
		{
			get
			{
				return this._MaDuong;
			}
			set
			{
				if ((this._MaDuong != value))
				{
					this.OnMaDuongChanging(value);
					this.SendPropertyChanging();
					this._MaDuong = value;
					this.SendPropertyChanged("MaDuong");
					this.OnMaDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuong", DbType="NVarChar(60)")]
		public string TenDuong
		{
			get
			{
				return this._TenDuong;
			}
			set
			{
				if ((this._TenDuong != value))
				{
					this.OnTenDuongChanging(value);
					this.SendPropertyChanging();
					this._TenDuong = value;
					this.SendPropertyChanged("TenDuong");
					this.OnTenDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuan", DbType="Int")]
		public System.Nullable<int> MaQuan
		{
			get
			{
				return this._MaQuan;
			}
			set
			{
				if ((this._MaQuan != value))
				{
					if (this._QuanHuyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanChanging(value);
					this.SendPropertyChanging();
					this._MaQuan = value;
					this.SendPropertyChanged("MaQuan");
					this.OnMaQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuongPho_QuanAn", Storage="_QuanAns", ThisKey="MaDuong", OtherKey="MaDuong")]
		public EntitySet<QuanAn> QuanAns
		{
			get
			{
				return this._QuanAns;
			}
			set
			{
				this._QuanAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanHuyen_DuongPho", Storage="_QuanHuyen", ThisKey="MaQuan", OtherKey="id", IsForeignKey=true)]
		public QuanHuyen QuanHuyen
		{
			get
			{
				return this._QuanHuyen.Entity;
			}
			set
			{
				QuanHuyen previousValue = this._QuanHuyen.Entity;
				if (((previousValue != value) 
							|| (this._QuanHuyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanHuyen.Entity = null;
						previousValue.DuongPhos.Remove(this);
					}
					this._QuanHuyen.Entity = value;
					if ((value != null))
					{
						value.DuongPhos.Add(this);
						this._MaQuan = value.id;
					}
					else
					{
						this._MaQuan = default(Nullable<int>);
					}
					this.SendPropertyChanged("QuanHuyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QuanAns(QuanAn entity)
		{
			this.SendPropertyChanging();
			entity.DuongPho = this;
		}
		
		private void detach_QuanAns(QuanAn entity)
		{
			this.SendPropertyChanging();
			entity.DuongPho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanAn")]
	public partial class QuanAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TenQuan;
		
		private string _DiaChi;
		
		private System.Data.Linq.Binary _HinhAnh;
		
		private string _SDT;
		
		private System.Nullable<int> _MaDuong;
		
		private System.Nullable<int> _MaDanhMuc;
		
		private System.Nullable<double> _Diem;
		
		private System.Nullable<float> _Lat;
		
		private System.Nullable<float> _Long;
		
		private System.Nullable<System.TimeSpan> _GioBatDau;
		
		private System.Nullable<System.TimeSpan> _GioKetThuc;
		
		private System.Nullable<decimal> _GiaThapNhat;
		
		private System.Nullable<decimal> _GiaCaoNhat;
		
		private string _MoTa;
		
		private EntitySet<MonAn> _MonAns;
		
		private EntityRef<DuongPho> _DuongPho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTenQuanChanging(string value);
    partial void OnTenQuanChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnHinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMaDuongChanging(System.Nullable<int> value);
    partial void OnMaDuongChanged();
    partial void OnMaDanhMucChanging(System.Nullable<int> value);
    partial void OnMaDanhMucChanged();
    partial void OnDiemChanging(System.Nullable<double> value);
    partial void OnDiemChanged();
    partial void OnLatChanging(System.Nullable<float> value);
    partial void OnLatChanged();
    partial void OnLongChanging(System.Nullable<float> value);
    partial void OnLongChanged();
    partial void OnGioBatDauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioBatDauChanged();
    partial void OnGioKetThucChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioKetThucChanged();
    partial void OnGiaThapNhatChanging(System.Nullable<decimal> value);
    partial void OnGiaThapNhatChanged();
    partial void OnGiaCaoNhatChanging(System.Nullable<decimal> value);
    partial void OnGiaCaoNhatChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public QuanAn()
		{
			this._MonAns = new EntitySet<MonAn>(new Action<MonAn>(this.attach_MonAns), new Action<MonAn>(this.detach_MonAns));
			this._DuongPho = default(EntityRef<DuongPho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuan", DbType="NVarChar(100)")]
		public string TenQuan
		{
			get
			{
				return this._TenQuan;
			}
			set
			{
				if ((this._TenQuan != value))
				{
					this.OnTenQuanChanging(value);
					this.SendPropertyChanging();
					this._TenQuan = value;
					this.SendPropertyChanged("TenQuan");
					this.OnTenQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuong", DbType="Int")]
		public System.Nullable<int> MaDuong
		{
			get
			{
				return this._MaDuong;
			}
			set
			{
				if ((this._MaDuong != value))
				{
					if (this._DuongPho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDuongChanging(value);
					this.SendPropertyChanging();
					this._MaDuong = value;
					this.SendPropertyChanged("MaDuong");
					this.OnMaDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhMuc", DbType="Int")]
		public System.Nullable<int> MaDanhMuc
		{
			get
			{
				return this._MaDanhMuc;
			}
			set
			{
				if ((this._MaDanhMuc != value))
				{
					this.OnMaDanhMucChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMuc = value;
					this.SendPropertyChanged("MaDanhMuc");
					this.OnMaDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float")]
		public System.Nullable<double> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Real")]
		public System.Nullable<float> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="Real")]
		public System.Nullable<float> Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this.OnLongChanging(value);
					this.SendPropertyChanging();
					this._Long = value;
					this.SendPropertyChanged("Long");
					this.OnLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioBatDau", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioBatDau
		{
			get
			{
				return this._GioBatDau;
			}
			set
			{
				if ((this._GioBatDau != value))
				{
					this.OnGioBatDauChanging(value);
					this.SendPropertyChanging();
					this._GioBatDau = value;
					this.SendPropertyChanged("GioBatDau");
					this.OnGioBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioKetThuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioKetThuc
		{
			get
			{
				return this._GioKetThuc;
			}
			set
			{
				if ((this._GioKetThuc != value))
				{
					this.OnGioKetThucChanging(value);
					this.SendPropertyChanging();
					this._GioKetThuc = value;
					this.SendPropertyChanged("GioKetThuc");
					this.OnGioKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThapNhat", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaThapNhat
		{
			get
			{
				return this._GiaThapNhat;
			}
			set
			{
				if ((this._GiaThapNhat != value))
				{
					this.OnGiaThapNhatChanging(value);
					this.SendPropertyChanging();
					this._GiaThapNhat = value;
					this.SendPropertyChanged("GiaThapNhat");
					this.OnGiaThapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaCaoNhat", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaCaoNhat
		{
			get
			{
				return this._GiaCaoNhat;
			}
			set
			{
				if ((this._GiaCaoNhat != value))
				{
					this.OnGiaCaoNhatChanging(value);
					this.SendPropertyChanging();
					this._GiaCaoNhat = value;
					this.SendPropertyChanged("GiaCaoNhat");
					this.OnGiaCaoNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(200)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanAn_MonAn", Storage="_MonAns", ThisKey="id", OtherKey="MaQuanAn")]
		public EntitySet<MonAn> MonAns
		{
			get
			{
				return this._MonAns;
			}
			set
			{
				this._MonAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuongPho_QuanAn", Storage="_DuongPho", ThisKey="MaDuong", OtherKey="MaDuong", IsForeignKey=true)]
		public DuongPho DuongPho
		{
			get
			{
				return this._DuongPho.Entity;
			}
			set
			{
				DuongPho previousValue = this._DuongPho.Entity;
				if (((previousValue != value) 
							|| (this._DuongPho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuongPho.Entity = null;
						previousValue.QuanAns.Remove(this);
					}
					this._DuongPho.Entity = value;
					if ((value != null))
					{
						value.QuanAns.Add(this);
						this._MaDuong = value.MaDuong;
					}
					else
					{
						this._MaDuong = default(Nullable<int>);
					}
					this.SendPropertyChanged("DuongPho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MonAns(MonAn entity)
		{
			this.SendPropertyChanging();
			entity.QuanAn = this;
		}
		
		private void detach_MonAns(MonAn entity)
		{
			this.SendPropertyChanging();
			entity.QuanAn = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonAn")]
	public partial class MonAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMonAn;
		
		private string _TenMonAn;
		
		private System.Data.Linq.Binary _HinhAnh;
		
		private System.Nullable<int> _Gia;
		
		private int _MaQuanAn;
		
		private EntityRef<QuanAn> _QuanAn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonAnChanging(int value);
    partial void OnMaMonAnChanged();
    partial void OnTenMonAnChanging(string value);
    partial void OnTenMonAnChanged();
    partial void OnHinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnMaQuanAnChanging(int value);
    partial void OnMaQuanAnChanged();
    #endregion
		
		public MonAn()
		{
			this._QuanAn = default(EntityRef<QuanAn>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMonAn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMonAn
		{
			get
			{
				return this._MaMonAn;
			}
			set
			{
				if ((this._MaMonAn != value))
				{
					this.OnMaMonAnChanging(value);
					this.SendPropertyChanging();
					this._MaMonAn = value;
					this.SendPropertyChanged("MaMonAn");
					this.OnMaMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMonAn", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenMonAn
		{
			get
			{
				return this._TenMonAn;
			}
			set
			{
				if ((this._TenMonAn != value))
				{
					this.OnTenMonAnChanging(value);
					this.SendPropertyChanging();
					this._TenMonAn = value;
					this.SendPropertyChanged("TenMonAn");
					this.OnTenMonAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanAn", DbType="Int NOT NULL")]
		public int MaQuanAn
		{
			get
			{
				return this._MaQuanAn;
			}
			set
			{
				if ((this._MaQuanAn != value))
				{
					if (this._QuanAn.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQuanAnChanging(value);
					this.SendPropertyChanging();
					this._MaQuanAn = value;
					this.SendPropertyChanged("MaQuanAn");
					this.OnMaQuanAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanAn_MonAn", Storage="_QuanAn", ThisKey="MaQuanAn", OtherKey="id", IsForeignKey=true)]
		public QuanAn QuanAn
		{
			get
			{
				return this._QuanAn.Entity;
			}
			set
			{
				QuanAn previousValue = this._QuanAn.Entity;
				if (((previousValue != value) 
							|| (this._QuanAn.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanAn.Entity = null;
						previousValue.MonAns.Remove(this);
					}
					this._QuanAn.Entity = value;
					if ((value != null))
					{
						value.MonAns.Add(this);
						this._MaQuanAn = value.id;
					}
					else
					{
						this._MaQuanAn = default(int);
					}
					this.SendPropertyChanged("QuanAn");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
